# Generated by Django 6.0.2 on 2026-02-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_subforum_comment_post_subforum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Reply',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=''),
        ),
    ]
