# Generated by Django 6.0.2 on 2026-02-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_reply_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.CharField(max_length=8192),
        ),
    ]
