# Generated by Django 6.0.2 on 2026-02-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_reply_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='subforum',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
