# Generated by Django 6.0.2 on 2026-02-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_post_slug_subforum_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subforum',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='reply',
            name='author_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subforum',
        ),
    ]
